apiVersion: apps/v1
kind: Deployment
metadata:
  name: zoo1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zoo1
  template:
    metadata:
      labels:
        app: zoo1
    spec:
      containers:
      - name: zoo1
        image: confluentinc/cp-zookeeper:7.2.1
        resources:
          limits:
            memory: "1Gi"
        env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"
        - name: ZOOKEEPER_SERVER_ID
          value: "1"
        ports:
        - containerPort: 2181

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka1
  template:
    metadata:
      labels:
        app: kafka1
    spec:
      containers:
      - name: kafka1
        image: confluentinc/cp-kafka:7.2.1
        ports:
        - containerPort:  29092
          name:  kafka1-internal
        - containerPort: 9092
          name: kafka1-external
        resources:
          limits:
            memory: "2Gi"
        env:
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zoo1:2181"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: 'INTERNAL://kafka1:29092,LISTENER_EXTERNAL://localhost:32321'
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: "INTERNAL"
        - name: KAFKA_LISTENERS
          value: "INTERNAL://0.0.0.0:29092,LISTENER_EXTERNAL://0.0.0.0:9092"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "INTERNAL:PLAINTEXT,LISTENER_EXTERNAL:PLAINTEXT"
        - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
          value: 'true'
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - name: registry
        image: confluentinc/cp-schema-registry:5.5.3
        resources:
          limits:
            memory: "1Gi"
        env:
        - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
          value: "PLAINTEXT://kafka1:29092"
        - name: SCHEMA_REGISTRY_HOST_NAME
          value: "registry"
        ports:
        - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: zoo1
spec:
  selector:
    app: zoo1
  ports:
    - protocol: TCP
      port: 2181
      targetPort: 2181
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: kafka1
spec:
  selector:
    app: kafka1
  ports:
    - name: internal
      port: 29092
      targetPort: 29092
    - name: external
      port: 9092
      targetPort: 9092
      nodePort: 32321
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: registry
spec:
  selector:
    app: registry
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: NodePort
