apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: billing
    name: billing
    namespace: default
spec:
    progressDeadlineSeconds: 600
    replicas: 2
    selector:
        matchLabels:
            app: billing
    strategy:
        rollingUpdate:
            maxSurge: 25%
            maxUnavailable: 25%
        type: RollingUpdate
    template:
        metadata:
            labels:
                app: billing
        spec:
            containers:
                - name: billing
                  image: localhost:5000/billing:latest
                  imagePullPolicy: Always
                  resources: {}
                  ports:
                      - containerPort: 80
            restartPolicy: Always
            terminationGracePeriodSeconds: 31
status:
    availableReplicas: 2
    observedGeneration: 2
    readyReplicas: 2
    replicas: 2
    updatedReplicas: 2

---

apiVersion: v1
kind: Service
metadata:
  name: billing-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: billing
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30082